# Generated by Django 4.1.6 on 2023-02-16 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='circulation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='circulation.circulation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='circulation.ticket'),
            preserve_default=False,
        ),
    ]
