# Generated by Django 4.1.5 on 2023-02-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circulation',
            old_name='end_data',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='circulation',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
