# Generated by Django 3.2.2 on 2023-02-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0002_auto_20230211_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='circulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circulations', to='circulation.circulation'),
        ),
    ]
