# Generated by Django 4.1.6 on 2023-03-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0002_alter_betinfo_price_alter_circulation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=1, max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
