# Generated by Django 4.1.6 on 2023-02-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0002_user_circulation_user_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='draw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draw', to='circulation.command'),
        ),
    ]
