# Generated by Django 4.1.5 on 2023-02-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0002_rename_end_data_circulation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tour',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
