# Generated by Django 4.1.6 on 2023-02-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0003_match_draw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='draw',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
