# Generated by Django 4.1.6 on 2023-02-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0005_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='imag',
            field=models.FileField(upload_to=''),
        ),
    ]
