# Generated by Django 4.1.5 on 2023-02-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0005_match_result_a_match_result_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulation',
            name='end_date_current',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
