# Generated by Django 4.1.6 on 2023-02-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0006_alter_command_imag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('imag', models.FileField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Bet',
        ),
    ]
