# Generated by Django 4.1.6 on 2023-02-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0007_betinfo_delete_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='betinfo',
            name='lastname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
