# Generated by Django 4.1.5 on 2023-02-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0007_remove_match_draw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='imag',
            field=models.ImageField(upload_to='media'),
        ),
    ]
