# Generated by Django 4.1.6 on 2023-02-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0008_betinfo_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betinfo',
            name='imag',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
