# Generated by Django 4.1.5 on 2023-02-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0010_circulation_end_date_finsh_circulation_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circulation',
            old_name='end_date_finsh',
            new_name='end_date_finish',
        ),
    ]
